### ISSUE TITLE
Does not seem to work anymore

### ISSUE THREAD

**Issue by philipperemy** [antham/yogo#1]

**Comment by antham** [comment]
I just saw this comment because I didn't received any notifications...

Could you be a bit more specific ?

**Comment by philipperemy** [comment]
@antham no problem. It was long time ago so I don't remember quite well.

But I think I installed on my mac and I was not able to fetch the mails.

**Comment by antham** [comment]
Right I will have a look, thanks for the details

**Comment by philipperemy** [comment]
Thanks!

**Comment by antham** [comment]
It's fixed in v2.0.2 sorry for the delay

**Comment by philipperemy** [comment]
@antham Thanks! No problem!
