### ISSUE TITLE
"successfully flushed" whereas going to yopmail's web site still shows many emails!!!

### ISSUE THREAD

**Issue by liar666** [antham/yogo#118]
Hi,

I registered 10 accounts to a cloud service thanks to your app. Each registering goes in 3 steps:
- register email & receive a code by email
- register again with the code
- receive a confirmation email

I've written a script to do all that automatically, **then cleaning all the yopmail inboxes**

Unfortunately, inboxes are not flushed, contrarily to what your tool reports:

Indeed, last steps looks like:
```
./yogo inbox flush "xxx@yopmail.com"
Inbox "xxx@yopmail.com" successfully flushed
```

But when I go to the yopmail website, I still see the 3 emails (register1, register2, confirmation)

**Comment by antham** [comment]
I tried three times and it works for me, do you had a sleep between each try otherwise you can be blocked.

**Comment by antham** [comment]
I close this issue as it is working and there is no more feedback, feel free to reopen it if needed.
