### ISSUE TITLE
"Flush" reports OK when there are still emails in the box

### ISSUE THREAD

**Issue by liar666** [antham/yogo#122]
Hi,

Thanks a lot for the tool (& for the recent addition of "source" :) ).

I wrote a script to clean/flush some yopmail email addresses, right after I've registered to a cloud provider, so that registration links do not leak for too long. The script reads like this: 
```
acc=<prefix>
for i in {00..10}
do
  account="${acc}${i}@yopmail.com"
  yogo inbox flush "${account}"
  sleep 10
done
```
Generally, it returns green lines saying that all the email boxes have been cleaned.

However, when I "log in" the web interface of yopmail, I can see some of the boxes still have emails in them.

From what I understand, it happens when I hit too much yopmail's API (not sure of the rate limit though, as 10 sec pause seems reasonable - at least compared to manual flushing in the web interface). Then, when I go to the web interface and resolve the CAPTCHA I'm faced with, the problem resolves for some time. 

Not sure what you could do about it, but maybe there's an error/warning that is returned when the rate limit is reached (i.e. when a CAPTCHA is shown in the web interface) that you could catch and warn the user about?

Thanks

**Comment by antham** [comment]
Hi,
so I don't think I can do anything for the CAPTCHA in itself, we could add a strategy with some proxies, but I don't think it would succeed in the end.
Instead, I tried to catch when the CAPTCHA is popping, it was pretty cumbersome and as most of this software, it's a kind of hack but it seems to work so let me know in the end if it's effective on your side.
