### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by commonhimself** [antham/yogo#125]
Error: failure when fetching https://yopmail.com : request failed with error code 429 and body <!DOCTYPE HTML><html><head><meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"/><meta http-equiv="Pragma" content="no-cache"/><meta http-equiv="Expires" content="0"/><script>window.top.location.replace('/http429');</script></head></html>

I keep getting this error when running any inbox command. Message me on discord if you can when you respond to this, as I'm not active on here. My discord is "cxmmon".

**Comment by antham** [comment]
You are probably performing too much requests see #97 , check if you get a captcha in a browser and solve it.
