### ISSUE TITLE
Error 400 fetching emails

### ISSUE THREAD

**Issue by maxdeb59** [antham/yogo#135]
Hi, 

Thank you very much for the tool. 

Since last week, I have an error 400 while I am trying to fetch emails.

`Error: failure when fetching https://yopmail.com/consent?c=accept : request failed with error code 400 and body
`
 It seems to be linked to a change in the cookie consent modal UI.

Could you please have a look on the problem?

Thanks in advance.

**Comment by antham** [comment]
Hi, thanks for reporting.

I will have a look later on.

**Comment by antham** [comment]
The version 4.0.1 fix the issue @maxdeb59, let me know if there is still an issue.
