### ISSUE TITLE
My IP was banned from yopmail.com ?

### ISSUE THREAD

**Issue by atmadja40** [antham/yogo#41]
Hello, Excuse me in advance, I know that it may not be an issue with your project.
Anyway, after I made ~50 requests to yopmail, I now can't access yopmail.com from any device behind my router.
Yogo says : `2020/05/10 11:29:16 Get http://www.yopmail.com: dial tcp 87.98.250.141:80: i/o timeout`
With my browser, page doesn't load. Only with my phone over mobile network I can load the page.
Did it happen the same to someone?

**Comment by antham** [comment]
Hi,
have you tried to wait a bit and retry ?

I guess, it could happen with too much request.

**Comment by atmadja40** [comment]
Hello antham,

Thank you for your reply, I can reach the servers again since today.
Seems you are right.

Hope this would help others :) Have a nice day !
