### ISSUE TITLE
yopmail api stopped working

### ISSUE THREAD

**Issue by ChethanKumarGK** [antham/yogo#73]
Hi Team,

I am using(yogo.exe) this from past 1 month, suddenly it stoped working saying "no yopmail api version found" looks like some API got updated. 

@antham can you please guide us on the same.

**Comment by antham** [comment]
Hi, 
Thanks for reporting.

I see the UI changed but api calls seem to be the same, maybe it's linked to the cookie consent page.

I will have a look today when I will have more time.

Cheers.

**Comment by antham** [comment]
Several changes, I have a problem with the captcha probably because of a more agressive captcha policy.

**Comment by antham** [comment]
Hi @ChethanKumarGK, 

it's fixed pick the last version, sorry for the delay.

Cheers.

**Comment by ChethanKumarGK** [comment]
Thanks @antham for the prompt fix, with in short time. :)
