### ISSUE TITLE
yogo Issue - Yopmail update (Captcha)

### ISSUE THREAD

**Issue by Javier-bat** [antham/yogo#97]
Hi.
input
`./yogo inbox show helloworld 1`
output
 `
failure when fetching https://yopmail.com : request failed with error code 429 and body <!DOCTYPE HTML><html><head><meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"/><meta http-equiv="Pragma" content="no-cache"/><meta http-equiv="Expires" content="0"/><script>window.top.location.replace('/http429');</script></head></html>
`

**Comment by Javier-bat** [comment]
![imagen](https://user-images.githubusercontent.com/32001377/182935708-a80200a0-f26e-4f96-9cb3-2e5be0d82b0b.png)


how can i skip it? thx :)

**Comment by antham** [comment]
There is no solution, add a backoff or go through a proxy.

**Comment by enriluis** [comment]
maybe with[ mail.tm ](https://api.mail.tm/)  or Emailnator https://www.emailnator.com/' APIs  wen can build something similar  without chatpcha, the challenge make this project unusable for many people. i was testing but no solution to captcha.

**Comment by antham** [comment]
The goal of Yopmail is not to be used through automation otherwise an API would exists. This project is here for a simple automation usage that involved Yopmail but cannot be used for projects that require big usages.

**Comment by antham** [comment]
There is the ability to define a proxy https://github.com/antham/yogo#environment-variable and customize few variables around the request but it's probably not enough to circumvent reCAPTCHA

**Comment by liar666** [comment]
Same problem here. Tried a proxy, still same problem.
I understand it is not your fault, but that's just make your app unusable :(
Would it be possible to consider inserting a ML CAPTCHA solver lib?
https://duckduckgo.com/?t=lm&q=captcha+solver+library&atb=v341-1&ia=web

**Comment by antham** [comment]
>  I understand it is not your fault, but that's just make your app unusable :(

It's unusable if you want to do lot of request on yopmail, for a simple usage it's ok. When I have a captcha, I solve it in the browser and it's fine after.

>  Would it be possible to consider inserting a ML CAPTCHA solver lib?

No I won't do that.
